import { chmodSync, existsSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { runtimeDir } from '../platform/paths.ts';
// Generated by scripts/build-binaries.ts. Bun embeds these native helpers into compiled executables via the file loader.
// @ts-ignore TypeScript cannot type a generated extensionless asset import.
import darwinGlimpseHostPath from '../../.build/glimpse-hosts/darwin-arm64/glimpse' with { type: 'file' };
// @ts-ignore TypeScript cannot type a generated executable asset import.
import windowsGlimpseHostPath from '../../.build/glimpse-hosts/win32/glimpse.exe' with { type: 'file' };

export function isBunEmbeddedPath(path: string): boolean {
  return path.startsWith('/$bunfs/');
}

export function isCompiledExecutableUrl(url: string): boolean {
  return url.startsWith('file:///$bunfs/');
}

export function prepareCompiledGlimpseHost() {
  if (process.env.GLIMPSE_BINARY_PATH || process.env.GLIMPSE_HOST_PATH) return;

  const source = process.platform === 'darwin'
    ? darwinGlimpseHostPath
    : process.platform === 'win32'
      ? windowsGlimpseHostPath
      : undefined;
  if (!source || !isBunEmbeddedPath(source)) return;

  const suffix = process.platform === 'win32' ? '.exe' : '';
  const dest = join(runtimeDir(), `glimpse-host-${process.platform}-${process.arch}${suffix}`);
  const embeddedSize = statSync(source).size;

  if (!existsSync(dest) || statSync(dest).size !== embeddedSize) {
    writeFileSync(dest, readFileSync(source));
    chmodSync(dest, 0o755);
  }

  process.env.GLIMPSE_BINARY_PATH = dest;
}
